[package]
name = "mighty-bitey"
version = "0.1.0"
edition = "2024"

[dependencies]
alerta = "0.1.2"
gtk4 = "0.10.3"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
sha3 = "0.10.8"
